import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.scss";

const geistSans = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Listopia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode }>) {
  return (
		<html lang='ru'>
			<body className={`${geistSans.variable} ${geistSans.variable}`}>
				{children}
			</body>
		</html>
	)
}
