"use client"
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import LeftMenu from "@/intities/ui/left-menu/left-menu";
import React, { createContext, useState } from "react";
import { ModalProps } from "./types/global";
import '../app/styles/globals.scss'
import ModalAddTask from "@/shared/ui/modal-add-task/modal-add-task";

const geistSans = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Listopia",
  description: "Generated by create next app",
};

const modalContextProps: ModalProps = {
	openModal: false,
	setOpenModal: () => {}
}

export const ContextModal = createContext(modalContextProps)

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode }>) {
	const [openModal, setOpenModal] = useState<boolean>(false)
  return (
		<html lang='ru'>
			<body className={`${geistSans.variable}`}>
				<ContextModal.Provider value={{ openModal, setOpenModal }}>
					<div className='wrapper__flex'>
						<div className=''>
							<LeftMenu />
						</div>
						<div className=''>{children}</div>
					</div>
						<ModalAddTask />
				</ContextModal.Provider>
			</body>
		</html>
	)
}
