import { Metadata } from "next"
import "../app/styles/globals.scss"
import StoreProvider from "@/redux/store-proveder"

export const metadata: Metadata = {
  title: "Listopia",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ru">
      <body className="">
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  )
}
